#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-wildfly-openssl
Version  : 1.0.4.final
Release  : 4
URL      : https://github.com/wildfly/wildfly-openssl/archive/1.0.4.Final.tar.gz
Source0  : https://github.com/wildfly/wildfly-openssl/archive/1.0.4.Final.tar.gz
Source1  : https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl-parent/1.0.4.Final/wildfly-openssl-parent-1.0.4.Final.pom
Source2  : https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.jar
Source3  : https://repo1.maven.org/maven2/org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-wildfly-openssl-data = %{version}-%{release}

%description
OpenSSL Bindings for Java
=========================
This project provides OpenSSL bindings for Java. As much as possible they attempt to use existing JSSE API's, so the
SSLContext should be usable as a drop in replacement for applications that are currently using JSSE.

%package data
Summary: data components for the mvn-wildfly-openssl package.
Group: Data

%description data
data components for the mvn-wildfly-openssl package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl-parent/1.0.4.Final
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl-parent/1.0.4.Final/wildfly-openssl-parent-1.0.4.Final.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl/1.0.4.Final
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl/1.0.4.Final
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl-parent/1.0.4.Final/wildfly-openssl-parent-1.0.4.Final.pom
/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.jar
/usr/share/java/.m2/repository/org/wildfly/openssl/wildfly-openssl/1.0.4.Final/wildfly-openssl-1.0.4.Final.pom
